### PR TITLE
Update StatusParser.java

### PR DESCRIPTION
**Pull request by fuutott**
Change name parser for Nut UPSes. Should use name as defined in ups.conf [brackets]

### CODE REVIEW

**Review by norkator — APPROVED** [review]

**Review by norkator — COMMENTED** [review]
@bo0tzz can you give input about this change made by @fuutott ?

**Comment by bo0tzz** [comment]
The NUT docs list a `device.mfr` field, but I can't find anything about the value it got changed to here. This change looks incorrect to me, but I can't really back that up with any arguments.

**Comment by fuutott** [comment]
As it is now app gives ups Name as American Power Conversions. As its using.mfr field.
BEGIN LIST VAR is a bit hacky but would give correct infi


BEGIN LIST VAR rack
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 50
battery.runtime: 4800
battery.runtime.low: 600
battery.type: PbAc
battery.voltage: 27.3
battery.voltage.nominal: 24.0
device.mfr: American Power Conversion: 
device.model: Smart-UPS 1500
device.serial: AS1944240766 : 
device.type: ups
driver.name: usbhid-ups
driver.parameter.bus: 002
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 15
driver.parameter.port: auto
driver.parameter.product: Smart-UPS 1500 FW:UPS 09.3 / ID=18
driver.parameter.productid: 0003
driver.parameter.serial: AS1944240766
driver.parameter.synchronous: no
driver.parameter.vendor: American Power Conversion
driver.parameter.vendorid: 051D
driver.version: 2.7.4
driver.version.data: APC HID 0.96
driver.version.internal: 0.41
ups.beeper.status: disabled
ups.delay.shutdown: 20
ups.firmware: UPS 09.3 / ID=18
ups.mfr: American Power Conversion: 
ups.mfr.date: 2019/10/29
ups.model: Smart-UPS 1500
ups.productid: 0003
ups.serial: AS1944240766 : 
ups.status: OL
ups.timer.reboot: -1
ups.timer.shutdown: -1
ups.vendorid: 051d
END LIST VAR rack

**Comment by norkator** [comment]
Reverted this change. It will become even more hacky since all fields ended with `:` and now  `BEGIN LIST VAR rack` only has space. This makes this change messy.

**Pull request merged**
