### PR TITLE
Refactor status parser implementation and fix NMC parsing

### PR DESCRIPTION
**Pull request by bo0tzz**
I got slightly carried away, so this PR contains a few (related) things:
1. I refactored the status parsing logic from a big if/else tree to a (hopefully) more readable structure based on pairing text labels with the appropriate setter methods (fixes bo0tzz/apcupsd-monitor#2)
2. I added some test cases for the above logic in order to do the refactor without breaking things
3. I added some fields that were missing from the NMC status parsing, the view in the app should now hopefully be complete (fixes bo0tzz/apcupsd-monitor#1)
4. I worked around a bug in the NMC SSH server, where sending too many commands at the same time causes it to seize up and close the connection without sending the full response.

There's a lot going on in this PR, so of course if there are parts you're not interested in just let me know and I will remove/fix them. Any other comments are always welcome too.

### CODE REVIEW

**Comment by norkator** [comment]
@bo0tzz  "if there are parts you're not interested" I'm interested of all changes. I'm not great developer code wise myself so these refactors are more than welcome. I especially like what you did for status parsing. Also you added tests which is big plus. I will thoroughly review this in coming hours.

**Review by norkator — APPROVED** [review]

**Comment by norkator** [comment]
I already made release with earlier changes. I release these later if theres more changes coming. Added draft release tag https://github.com/norkator/apcupsd-monitor/releases/tag/untagged-53f82f68c48ff40d772c

**Comment by bo0tzz** [comment]
> I release these later if theres more changes coming.

👍, I have event log loading for the NMC in the pipeline now and that'll hopefully be done tomorrow. I think that should cover NMC feature - wise, I'll see if I spot anything else to do after that.

**Comment by norkator** [comment]
Yes no worries/hurries.. I check back here time to time. Thanks for contributions.

**Pull request merged**
